name: PR Validation

on:
  pull_request:
  workflow_dispatch: # Allow manual triggering of the workflow for testing purposes

permissions:
  contents: read

jobs:
  test-and-analysis:
    name: Test and Analysis (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Bootstrap dependencies
        shell: pwsh
        run: ./build.ps1 bootstrap

      - name: Run tests with coverage
        shell: pwsh
        run: ./build.ps1 test -TestReport -CoverageReport

      - name: Run static analysis
        shell: pwsh
        run: ./build.ps1 analysis

      - name: Upload test results to Codecov
        if: always() && job.status != 'cancelled'
        uses: codecov/codecov-action@v5
        with:
          report_type: test_results
          files: ./artifacts/results/junit.xml
          disable_search: true
          env_vars: OS
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Upload coverage to Codecov
        if: always() && job.status != 'cancelled'
        uses: codecov/codecov-action@v5
        with:
          report_type: coverage
          files: ./artifacts/results/coverage.cobertura.xml
          disable_search: true
          env_vars: OS
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
